[[pages]]
path="main.py"
name="Home"
icon="ğŸŸï¸"

[[pages]]
path="./pages/batting-stats.py"
name="Batting"
icon="âš¾ï¸"

[[pages]]
path="./pages/pitching-stats.py"
name="Pitching"
icon="ğŸ§¢"

[[pages]]
path="./pages/team-stats.py"
name="Team Statistics"
icon="ğŸ“Š"

[[pages]]
path="./pages/about.py"
name="About"
icon="ğŸ““"